/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to create an actual road layout with physics
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { RoadStraight } from './models/RoadStraight';
import { RoadCorner } from './models/RoadCorner';
import { RoadWall } from './models/RoadWall';
import { RoadCornerWall } from './models/RoadCornerWall';

type GLTFResult = GLTF & {
    nodes: {
        road_corner: THREE.Mesh;
        road_corner_curved: THREE.Mesh;
        road_junction: THREE.Mesh;
        road_straight: THREE.Mesh;
        road_straight_crossing: THREE.Mesh;
        road_tsplit: THREE.Mesh;
    };
    materials: {
        citybits_texture: THREE.MeshStandardMaterial;
    }
};

// Road piece size (each tile is 8 units - quadrupled from original)
const TILE_SIZE = 8;

const WALL_HEIGHT = 2;
const WALL_THICKNESS = 0.3;

// Reusable road piece component with physics



export function Road(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/models/Road Bits.glb') as unknown as GLTFResult;

    const straightGeo = nodes.road_straight.geometry;
    const cornerGeo = nodes.road_corner_curved.geometry;
    const mat = materials.citybits_texture;

    // Create a simple rectangular road circuit
    // Layout (looking from above):
    //   ┌─────────────────┐
    //   │                 │
    //   │                 │
    //   │                 │
    //   │                 │
    //   │                 │
    //   │                 │
    //   └─────────────────┘
    // 
    // Track dimensions: 7 tiles wide (X: -1 to 5) x 8 tiles tall (Z: 0 to 7)
    // Corners at: (-1,0), (5,0), (-1,7), (5,7)
    // Bottom/Top rows: X from 0 to 4 (5 tiles each)
    // Left/Right columns: Z from 1 to 6 (6 tiles each)

    return (
        <group {...props} dispose={null}>
            {/* Bottom row - straight pieces (X: 0 to 4, Z: 0) */}
            <RoadStraight position={[0, 0, 0]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE, 0, 0]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 2, 0, 0]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 3, 0, 0]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 4, 0, 0]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />

            {/* Top row - straight pieces (X: 0 to 4, Z: 7) */}
            <RoadStraight position={[0, 0, TILE_SIZE * 7]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE, 0, TILE_SIZE * 7]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 2, 0, TILE_SIZE * 7]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 3, 0, TILE_SIZE * 7]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 4, 0, TILE_SIZE * 7]} rotationY={Math.PI / 2} geometry={straightGeo} material={mat} />

            {/* Left column - straight pieces (X: -1, Z: 1 to 6) */}
            <RoadStraight position={[-TILE_SIZE, 0, TILE_SIZE]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[-TILE_SIZE, 0, TILE_SIZE * 2]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[-TILE_SIZE, 0, TILE_SIZE * 3]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[-TILE_SIZE, 0, TILE_SIZE * 4]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[-TILE_SIZE, 0, TILE_SIZE * 5]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[-TILE_SIZE, 0, TILE_SIZE * 6]} rotationY={0} geometry={straightGeo} material={mat} />

            {/* Right column - straight pieces (X: 5, Z: 1 to 6) */}
            <RoadStraight position={[TILE_SIZE * 5, 0, TILE_SIZE]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 5, 0, TILE_SIZE * 2]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 5, 0, TILE_SIZE * 3]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 5, 0, TILE_SIZE * 4]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 5, 0, TILE_SIZE * 5]} rotationY={0} geometry={straightGeo} material={mat} />
            <RoadStraight position={[TILE_SIZE * 5, 0, TILE_SIZE * 6]} rotationY={0} geometry={straightGeo} material={mat} />

            {/* Corners - positioned to connect the rows and columns */}
            {/* Bottom-left corner (X: -1, Z: 0) - connects bottom row to left column */}
            <RoadCorner position={[-TILE_SIZE, 0, 0]} rotationY={4 * (Math.PI / 2)} geometry={cornerGeo} material={mat} />
            {/* Bottom-right corner (X: 5, Z: 0) - connects bottom row to right column */}
            <RoadCorner position={[TILE_SIZE * 5, 0, 0]} rotationY={-Math.PI / 2} geometry={cornerGeo} material={mat} />
            {/* Top-left corner (X: -1, Z: 7) - connects top row to left column */}
            <RoadCorner position={[-TILE_SIZE, 0, TILE_SIZE * 7]} rotationY={Math.PI / 2} geometry={cornerGeo} material={mat} />
            {/* Top-right corner (X: 5, Z: 7) - connects top row to right column */}
            <RoadCorner position={[TILE_SIZE * 5, 0, TILE_SIZE * 7]} rotationY={2 * (Math.PI / 2)} geometry={cornerGeo} material={mat} />

            {/* ============ CURVED CORNER WALLS ============ */}
            {/* Bottom-left corner - outer wall (curves around the outside) */}
            {/* <RoadCornerWall
                position={[-TILE_SIZE, 0, 0]}
                rotationY={Math.PI}
                radius="outer"
            /> */}
            {/* Bottom-left corner - inner wall (curves around the inside) */}
            <RoadCornerWall
                position={[-TILE_SIZE - 3, 0, -3]}
                rotationY={Math.PI}
                radius="inner"
            />


            {/* Bottom-right corner - inner wall */}
            <RoadCornerWall
                position={[TILE_SIZE * 5 + 3, 0, -3]}
                rotationY={-Math.PI / 2}
                radius="inner"
            />

            {/* Top-left corner - inner wall */}
            <RoadCornerWall
                position={[-TILE_SIZE - 3, 0, TILE_SIZE * 7 + 3]}
                rotationY={Math.PI / 2}
                radius="inner"
            />

            {/* Top-right corner - inner wall */}
            <RoadCornerWall
                position={[TILE_SIZE * 5 + 3, 0, TILE_SIZE * 7 + 3]}
                rotationY={0}
                radius="inner"
            />

            {/* ============ COLLISION WALLS ============ */}
            {/* 
                Track boundaries - walls on both sides of the road
                Outer walls: Outside edge of the track
                Inner walls: Inside edge of the track (forming the center island)
                Wall height starts at ground level to prevent vehicle from escaping
            */}

            {/* OUTER WALLS - Surrounding the entire track */}
            {/* Outer Left Wall (runs along Z axis, outside the left column) */}
            <RoadWall
                position={[-TILE_SIZE - TILE_SIZE / 2, WALL_HEIGHT / 2, TILE_SIZE * 3.5]}
                args={[WALL_THICKNESS, WALL_HEIGHT, TILE_SIZE * 8]}
            />
            {/* Outer Right Wall (runs along Z axis, outside the right column) */}
            <RoadWall
                position={[TILE_SIZE * 5 + TILE_SIZE / 2, WALL_HEIGHT / 2, TILE_SIZE * 3.5]}
                args={[WALL_THICKNESS, WALL_HEIGHT, TILE_SIZE * 8]}
            />
            {/* Outer Bottom Wall (runs along X axis, outside the bottom row) */}
            <RoadWall
                position={[TILE_SIZE * 2, WALL_HEIGHT / 2, -TILE_SIZE / 2]}
                args={[TILE_SIZE * 7, WALL_HEIGHT, WALL_THICKNESS]}
            />
            {/* Outer Top Wall (runs along X axis, outside the top row) */}
            <RoadWall
                position={[TILE_SIZE * 2, WALL_HEIGHT / 2, TILE_SIZE * 7 + TILE_SIZE / 2]}
                args={[TILE_SIZE * 7, WALL_HEIGHT, WALL_THICKNESS]}
            />

            {/* INNER WALLS - The center island inside the track */}
            {/* Inner Left Wall (inside the track, right side of left column) */}
            <RoadWall
                position={[-TILE_SIZE / 2, WALL_HEIGHT / 2, TILE_SIZE * 3.5]}
                args={[WALL_THICKNESS, WALL_HEIGHT, TILE_SIZE * 6]}
            />
            {/* Inner Right Wall (inside the track, left side of right column) */}
            <RoadWall
                position={[TILE_SIZE * 4 + TILE_SIZE / 2, WALL_HEIGHT / 2, TILE_SIZE * 3.5]}
                args={[WALL_THICKNESS, WALL_HEIGHT, TILE_SIZE * 6]}
            />
            {/* Inner Bottom Wall (inside the track, top side of bottom row) */}
            <RoadWall
                position={[TILE_SIZE * 2, WALL_HEIGHT / 2, TILE_SIZE / 2]}
                args={[TILE_SIZE * 5, WALL_HEIGHT, WALL_THICKNESS]}
            />
            {/* Inner Top Wall (inside the track, bottom side of top row) */}
            <RoadWall
                position={[TILE_SIZE * 2, WALL_HEIGHT / 2, TILE_SIZE * 6 + TILE_SIZE / 2]}
                args={[TILE_SIZE * 5, WALL_HEIGHT, WALL_THICKNESS]}
            />
        </group>
    );
}

useGLTF.preload('/models/Road Bits.glb');